// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLSCJhI26xeluUkeJGYymGmwMqDYjL1uc',
    appId: '1:80237520787:web:6356288f711a530ed02a66',
    messagingSenderId: '80237520787',
    projectId: 'spotifyclone-244fd',
    authDomain: 'spotifyclone-244fd.firebaseapp.com',
    storageBucket: 'spotifyclone-244fd.appspot.com',
    measurementId: 'G-FGQ27MR09B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv9LcwE8ytIZLNgt8YQaqDsxTCUorTNBE',
    appId: '1:80237520787:android:90c47f5f5ecfb0a7d02a66',
    messagingSenderId: '80237520787',
    projectId: 'spotifyclone-244fd',
    storageBucket: 'spotifyclone-244fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWJWLwOSpBdmWMqIOtXnef6AQ_1n17I30',
    appId: '1:80237520787:ios:6c6dd8f56fd86e46d02a66',
    messagingSenderId: '80237520787',
    projectId: 'spotifyclone-244fd',
    storageBucket: 'spotifyclone-244fd.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );
}
